version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: techtrack
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=techtrack
      - DB_USER=user
      - DB_PASSWORD=password
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - db
    environment:
      - DATABASE_USER=user
      - DATABASE_HOST=db
      - DATABASE_NAME=techtrack
      - DATABASE_PASSWORD=password
      - DATABASE_PORT=5432
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:

