# Generated by Django 5.1.1 on 2024-09-15 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders_app', '0001_initial'),
        ('technicians_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='technicians_app.technician'),
        ),
    ]
